runtime: java11
instance_class: B4_1G
basic_scaling:
  max_instances: 1
env_variables:
  SPRING_PROFILES_ACTIVE: "prod,gCloudStandard"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto