spring:
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mail:
  enabled: true
# mail.bcc=

build:
  version: @project.version@
  timestamp: @timestamp@

accountrpt:
  parse:
    headers:
      Section1:
        company-name: true
        underline: no_underline
      Section2:
        company-name: false
        underline: after_last
      Section3:
        company-name: true
        underline: before_last
      Section4:
        company-name: true
        underline: before_last
      Section5:
        company-name: true
        underline: before_last
      Section6:
        company-name: true
        underline: before_last
      Contents:
        company-name: true
        underline: after_last
  merge:
    pre-parse-sheets:
      - Control
      - "Dir info"
      - Section3
      - Section4
      - Section6
    template-path: allDocs
    template-file-property: xlsx.template.name
    merge-cell-colors:
      - 4F81BD
      - 8064A2
  mail:
    template: 'job-template.html'
    subject-prefix: 'Accounting Report For '
excel-extract:
  mail:
    template: 'excel-extract-template.html'
    subject-prefix: 'D-biz Report For '
  merge:
    pre-parse-sheets:
      - Control
      - P&L
    template-path: dBizFunding
    template-file-property: xlsx.template.dBizFunding.name
    merge-cell-colors:
      - 5B9BD5
  parse:
    keep-formula-color: 92D050
server:
  error:
    include-message: always
