storage:
  persistent:
    folder: ../local/files/
  temp:
    folder: ../local/temp/
    retention:
      days: 1

mail:
  enabled: false
  sender: ketonemaniac@gmail.com

mongo:
  database:
    name: testing

security:
  enable: false

logging:
  level:
    net.ketone.accrptgen.task.gen.merge: DEBUG