# This is for flexible environment only
# https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml

runtime: java
env: flex
runtime_config:
   jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

automatic_scaling:
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
