runtime: java11
instance_class: B4_1G
basic_scaling:
  max_instances: 1
env_variables:
  JAVA_USER_OPTS: "-Djava.util.logging.config.file=WEB-INF/classes/logging.properties"
  SPRING_PROFILES_ACTIVE: "staging,gCloudStandard"
