apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: acctrptgen
spec:
  template:
    spec:
      containers:
        - image: asia-east1-docker.pkg.dev/accountrptgen-hk/accountrptgen/app:latest
          env:
            - name: JAVA_USER_OPTS
              value: -Djava.util.logging.config.file=WEB-INF/classes/logging.properties
            - name: SPRING_PROFILES_ACTIVE
              value: prod,gCloudStandard,cloudRun
          resources:
            limits:
              memory: 1G